version: "3.9"

services:
  langserve:
    build:
      context: .
      dockerfile: infra/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./apps:/code/apps
    depends_on:
      - weaviate
      - neo4j
      - graphiti
    command: >
      uvicorn apps.email_manager.main:app --host ${EMAIL_MANAGER_HOST:-0.0.0.0} --port ${EMAIL_MANAGER_PORT:-8000} --reload

  weaviate:
    image: semitechnologies/weaviate:1.25.6
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate

  neo4j:
    image: neo4j:5.17-community
    restart: on-failure
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD:-changeme}"
    volumes:
      - neo4j_data:/data

  graphiti:
    image: zepai/graphiti:latest
    restart: on-failure
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-changeme}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8100:8080"
    depends_on:
      - neo4j

  n8n:
    image: n8nio/n8n:1.41
    restart: on-failure
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  weaviate_data:
  neo4j_data:
  n8n_data:
